name: Check & Test latest parsers

on:
    push:
        branches:
            - master

jobs:
    check-and-build:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repository 🌏
                uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 # v6.0.2

            -   name: Set up Java enviroment 🔧
                uses: actions/setup-java@b622de1dfa918ecc0ab28f40cd42e3c3752cd6c5 # v5.2.0
                with:
                    java-version: '17'
                    distribution: 'temurin'

            -   name: Set up Gradle enviroment 📦
                uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v6.1.0
                with:
                    gradle-version: '9.3.1'

            -   name: Compile the library 🚀
                run: ./gradlew compileKotlin
